set __fish_git_prompt_showdirtystate 'yes'
set __fish_git_prompt_color_branch yellow
set __fish_git_prompt_color_prefix yellow
set __fish_git_prompt_showcolorhints 'yes'
set __fish_git_prompt_show_informative_status 'yes'
